version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestRestart1704Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
services:
- serviceName: project.testrestart1704.integrations:gcd1704
  packages:
  - name: TestRestart1704Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2047
